### ISSUE TITLE
Need to press multiple times before undo/redo happens

### ISSUE THREAD

**Issue by Croutonix** [PPartisan/RunDo#3]
Sometimes when I undo, I need to do it a couple times before it happens (2-4 times) Only the cursor moves but the text doesn't change. Is this normal?

**Comment by PPartisan** [comment]
No, that shouldn't happen. Text should only be saved to the Undo queue when a change occurs, so an `undo()` call should always return something unique. Have you got a sample I could take a look at that replicates the issue?

**Comment by Croutonix** [comment]
Sample project: [RunDoBug.zip](https://github.com/PPartisan/RunDo/files/572651/RunDoBug.zip)
Nothing special except basic implementation of RunDo. Maybe I'm forgetting something which causes this. Just write a bit of text and undo it a couple times, it'll eventually happen. Cursor moves but nothing is undone on first click, it undoes only on second click.

**Comment by Croutonix** [comment]
Could you reproduce the bug?

**Comment by PPartisan** [comment]
I wasn't able to reproduce it unfortunately, although I do have a couple of ideas on how to make saves to the Undo queue more robust to eliminate any possibility of duplicates. Text changes are currently saved to a modified `ArrayDeque`, and switching this to something like a `LinkedHashSet` would make it impossible for duplicate elements to exist, for instance.

I wont be able to look into this issue in detail however for at least a week, maybe longer.

**Comment by Croutonix** [comment]
I guess this was probably just because I added spans and it called the text change listener, adding a duplicate undo in queue.
